export const GOODS_LIST_SORT = 'GOODS_LIST_SORT';
export const GOODS_LIST_GETDATA = 'GOODS_LIST_GETDATA';
export const GOODS_LIST_UPDATAPARAMS = 'GOODS_LIST_UPDATAPARAMS';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
